### ISSUE TITLE
Create Warning/Error when include directory does not exist

### ISSUE THREAD

**Issue by gmoro** [SUSE-Enceladus/keg#113]
I had a typo in one of the include (capital vs non-capital letters) and I just didn't get the include in place with no warning, if path not found we should do something about it.

**Comment by jgleissner** [comment]
That keg doesn't throw an error is intentional, as it is fine to reference sub directories that may not exist. If you for example have additional settings (like, billing codes) in a private repository you can still include those in a public recipe, and when generating from the public recipe only you'd simply miss those.

A warning however may certainly be in order. I'm just a little concerned that people could start worrying about warnings when building from a repo setup such as described, even though it's perfectly fine. We could make it a debug message, but that makes mistakes harder to miss, of course.

**Comment by jgleissner** [comment]
An info would be a good middle ground. People might still wonder whether there's something wrong though when they see the message, but it's probably better than hiding the message in the debug output.
